apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: default
    labels:
      name: default
    annotations:
      name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: aws-secret
      key: creds
