---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xblogs.fcuic.example
spec:
  group: fcuic.example
  names:
    kind: XBlog
    plural: xblogs
  claimNames:
    kind: BlogClaim
    plural: blogclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              environment:
                description: "Environment name"
                type: string
              region:
                description: "Region where to deploy resources"
                type: string
              vpcCidr:
                type: string
                description: "CIDR block for the VPC."
              subnetCidr:
                type: string
                description: "CIDR block for the Subnet."
              ami:
                type: string
                description: "EC2 AMI"
              instanceType:
                description: "Instance size"
                type: string
                oneOf:
                  - pattern: '^small$'
                  - pattern: '^medium$'
                  - pattern: '^large$'
            required:
              - environment
              - region
              - vpcCidr
              - subnetCidr
              - ami
              - instanceType